# Generated by Django 4.1 on 2022-10-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('1', 'Cash'), ('2', 'Credit Or Debit Card'), ('3', 'Paypal')], default='1', max_length=25)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=3)),
                ('captured_amount', models.DecimalField(decimal_places=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
