# Generated by Django 4.1 on 2022-10-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approve',
        ),
        migrations.AlterField(
            model_name='review',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
