# Generated by Django 4.1 on 2022-10-20 19:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
