# Generated by Django 4.1 on 2022-10-20 20:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_address_days_address_end_time_address_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=150, null=True),
        ),
    ]
