# Generated by Django 4.1 on 2022-10-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='balance_amount',
        ),
    ]
