# Generated by Django 4.1 on 2022-10-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('is_paid', models.BooleanField()),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Acceptance'), ('3', 'Rejected')], default='1', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
